name: 'sentinance'
version: '1.0.0'
config-version: 2

profile: 'sentinance'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  start_date: '2024-01-01'

models:
  sentinance:
    staging:
      +materialized: incremental
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
